### DISCUSSION TITLE
【征询意见】 将主页挂载到gitcode？

### DISCUSSION THREAD

**Discussion by MFn233** [MFn233/PCL-Mainpage#18] [公告]
**设想**：

使用webhook，将github的内容镜像到gitcode，

再创建gitcode pages，实现挂载。

**需要解决的问题**:

gitcode同步不了github的内容，会显示失效

所以该怎么实现：）

**Comment by MFn233** [comment]
难道是要手动？难道是要手动？难道是要手动？难道是要手动？难道是要手动？

**Comment by Ad-closeNN** [comment]
为什么想挂载到gitcode
现在不好吗.png

**Reply by MFn233** [reply]
因为sipc的cdn不是长期的选择
每次更新我都得喊他同步

**Reply by Ad-closeNN** [reply]
Github 镜像cdn应该可以？比如[这个](https://jsd.cdn.zzko.cn/gh/Mfn233/PCL-mainpage/Custom.xaml)
`https://jsd.cdn.zzko.cn`
还有[这个](https://jsd.onmicrosoft.cn/gh/Ad-closeNN/aft/Custom.xaml)
`https://cdn.onmicrosoft.cn/`

应该能用吧，都是国内的，一般15ms~50ms(没测过，在[这里](https://github.com/runningcheese/MirrorSite)找到的）。但他俩都是公益的cdn，我怕扛不住
难道龙猫不让交github cdn...?

**Reply by MFn233** [reply]
不让
github相关都不行

**Reply by Ad-closeNN** [reply]
GPT 曰:
——

**user**: 我在github上有一个文件。但是他常常要更新。cdn不好要付钱。gitee（国内另一个代码托管平台）的话要手动拉取，不方便。有什么方法吗

您可以考虑使用 GitHub Actions 来自动同步文件到 Gitee 上。GitHub Actions 是 GitHub 提供的一项功能，可以让您在代码仓库中运行自定义的自动化任务。

下面是一种方法：

1. **在 GitHub 上设置 Actions**：在您的 GitHub 仓库中，创建一个新的 Workflow 文件（例如 `.github/workflows/sync.yml`），用于定义同步任务。

2. **编写同步任务脚本**：在 Workflow 文件中编写一个脚本，使其在 GitHub 上的每次更新时自动将文件同步到 Gitee。您可以使用 Shell 脚本或者其他脚本语言编写这个任务。

3. **配置 Secrets**：在 GitHub 仓库的 Settings > Secrets 页面中，设置 Gitee 的用户名和密码等敏感信息，以便于脚本能够访问 Gitee 仓库进行同步。

4. **触发同步任务**：每当 GitHub 仓库有更新时，GitHub Actions 将自动运行同步任务，将文件同步到 Gitee。

这样一来，您就能够实现自动同步文件到 Gitee 上，而无需手动拉取。

<details>
<summary>GPT3.5生成的脚本帮助（谨慎展开）</summary>

**user**: 什么脚本啊？帮我弄弄

好的，下面是一个简单的示例脚本，用于在 GitHub Actions 中将文件同步到 Gitee。这个示例使用 Shell 脚本，并假设您希望将 GitHub 仓库中的 `file.txt` 文件同步到 Gitee 中。

1. 在您的 GitHub 仓库中创建一个名为 `.github/workflows/sync.yml` 的文件，内容如下：

```yaml
name: Sync to Gitee

on:
  push:
    branches:
      - main  # 可以根据您的实际需求修改分支名

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sync to Gitee
      env:
        GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
        GITEE_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
      run: |
        # 修改成您的同步脚本
        bash ./sync_to_gitee.sh
```

2. 在您的仓库中创建一个名为 `sync_to_gitee.sh` 的脚本文件，内容如下：

```bash
#!/bin/bash

# Clone Gitee repository
git clone https://${GITEE_USERNAME}:${GITEE_PASSWORD}@gitee.com/your_username/your_repository

# Copy file from GitHub repository to Gitee repository
cp file.txt your_repository/

# Commit and push changes
cd your_repository
git add .
git commit -m "Sync file.txt from GitHub"
git push origin main
```

请确保将 `your_username` 和 `your_repository` 替换为您在 Gitee 上的用户名和仓库名称，并根据您的实际情况修改文件名和路径。

3. 在您的 GitHub 仓库的 Settings > Secrets 页面中，设置两个 Secrets：`GITEE_USERNAME` 和 `GITEE_PASSWORD`，分别为您在 Gitee 上的用户名和密码。

完成上述步骤后，每当您的 GitHub 仓库中有更新推送到 `main` 分支时，GitHub Actions 将自动运行同步任务，并将文件同步到 Gitee 中。
